### ISSUE TITLE
Should publicKeyToken be part of the code?

### ISSUE THREAD

**Issue by kaplanlior** [CIOIL/nopcommerce-elastic-search-plugin#2]
Yes, it's only the token and not the public key, but should be part of the code released?
https://github.com/CIOIL/nopcommerce-elastic-search-plugin/blob/b23f66c5ea50c9b87ef59d217ed643191b0e4bd2/app.config#L6

**Comment by ronenaTourism** [comment]
Hi,

From our standpoint, there is no problem with the token being part of the code you released.
You can read about the role of a Public Key Token in the configuration files here : https://stackoverflow.com/questions/1321419/what-is-the-role-of-public-key-token
If you think or feel otherwise,  please let us know.
[](https://stackoverflow.com/questions/1321419/what-is-the-role-of-public-key-token)

**Comment by ronenaTourism** [comment]
The assembly’s Public Key Token identifies it on a one-to-one basis and as far as we know, it doesn’t reveal any important information or considered as a security threat.
The following link is to Stackoverflow . You can find other related information there.
https://stackoverflow.com/questions/1321419/what-is-the-role-of-public-key-token
[](https://stackoverflow.com/questions/1321419/what-is-the-role-of-public-key-token)
